on: [push]

jobs:
    build:
        name: Course Documentation Project
        runs-on: ubuntu-latest
        steps:
            sudo: false
            language: python
            script:
                - pip install -r requirements.txt