#
# Action to build and publish Leo's Course Documentation Project.
# This action launces on GitHub, checks out the main brach (immediately
# after a push), builds the sphinx documents into an html tree,
# and deploys the html content on the gh-pages.
# 
# Leo Irakliotis - lgreco@gmail.com
#

#on: [push]
#jobs:
#    build-and-publish-cdp:
#        runs-on: ubuntu-latest
#        steps:
#            - uses: actions/checkout@main # make local copy of repo
#            - run: pip install sphinx
#            - run: pip install sphinx-rtd-theme
#            - run: pip install sphinxcontrib.gist
#            - run: sphinx-build -b html docs/source xyz # need to parameterize later
#            - uses: ad-m/github-push-action@master
#            with:
#                github_token: ${{ secrets.GITHUB_TOKEN }}
#                branch: gh-pages

name: Pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - run: sphinx-build -b html docs/source xyz # need to parameterize later
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
