#
# Action to build and publish Leo's Course Documentation Project.
# This action launces on GitHub, checks out the main brach (immediately
# after a push), builds the sphinx documents into an html tree,
# and deploys the html content on the gh-pages.
# 
# Leo Irakliotis - lgreco@gmail.com
#

on: [push]
jobs:
    build-and-publish-cdp:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main # make local copy of repo
            - run: pip install sphinx
            - run: pip install sphinx-rtd-theme
            - run: pip install sphinxcontrib.gist
            - run: sphinx-build -b html docs/source xyz # put everything in new xyz dir; need to parameterize later
            - run: cd xyz
            # Next:
            # Now that we have a directory with the html build, deploy it on gh-pages.
            - run: git branch gh-pages
            - run: git symbolic-ref HEAD refs/heads/gh-pages  # auto-switches branches to gh-pages
            - run: rm .git/index
            - run: git clean -fdx