on: [push]
jobs:
    publish-cdp:
        runs-on: ubuntu-latest
        steps:
            - run: pip install sphinx
            - run: pip install travis-sphinx
            - run: pip install sphinx-rtd-theme
            - run: pip install sphinxcontrib.gist
            - run: BOOK_VERSION=$(./get-current-version.sh) travis-sphinx build -s source
            