#
# Action to build and publish Leo's Course Documentation Project.
# This action launces on GitHub, checks out the main brach (immediately
# after a push), builds the sphinx documents into an html tree,
# and deploys the html content on the gh-pages.
# 
# Leo Irakliotis - lgreco@gmail.com
#

on: [push]
jobs:
    build-and-publish-cdp:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main # make local copy of repo
            - run: pip install sphinx
            - run: pip install sphinx-rtd-theme
            - run: pip install sphinxcontrib.gist
            - run: sphinx-build -b html docs/source xyz # need to parameterize later
actions:
- action: "EMAIL action"
  type: "EMAIL"
  title: "$title"
  from_name: "Buddy"
  content: "<b>${BUDDY_PIPELINE_NAME}</b> execution #${BUDDY_EXECUTION_ID}"
  recipients: "mike@buddy.works\nalex@buddy.works"
  send_as_html: true
  variables:
  - key: "title"
    value: "Pipeline executed successfully!"
